"""
Shared Pydantic v2 contracts for the Agentic AppSec Remediation Engine.

All data that flows between agents, tools, and storage layers is typed
through these models. Agents NEVER pass raw dicts across module boundaries.
"""

from .schemas import (
    # Constants
    MAX_ANCESTRY_DEPTH,
    MAX_TASK_QUEUE_SIZE,
    AgentActionStatus,
    AgentActionSummary,
    ASTNodeType,
    BatchQAResult,
    # Sandbox contracts
    CommandResult,
    CVEEnrichment,
    # Sub-models
    CWEEntry,
    EditRequest,
    EditResult,
    EditStatus,
    FailureCategory,
    FixPlan,
    FixPlanStatus,
    GroupRemediationStatus,
    IssueSource,
    IssueType,
    LineRange,
    LocalizedIssue,
    PatchAttempt,
    QAAttemptResult,
    QAEvaluation,
    QAFailureEvidence,
    RemediationTask,
    RoutingStrategy,
    SCARemediationStage,
    # Enumerations
    Severity,
    StateConsistencyEvent,
    SupervisorDecision,
    SupervisorRetryPlan,
    # Triage and QA contracts
    SystemContext,
    TaskAttemptSnapshot,
    # Task queue
    TaskSpawnRequest,
    TaskStatus,
    TrajectoryEvent,
    TrajectoryEventKind,
    TriageResult,
    UpdateRetryDiagnostics,
    ValidationResult,
    ValidationStatus,
    VulnerabilityGroup,
    # Core domain models
    VulnerabilityIssue,
    WorkaroundContext,
    WorkaroundEdit,
    WorkaroundPhase,
    WorkaroundReplayPlan,
    WorkerAttemptResult,
    WorkerExecutionDiagnostics,
)

__all__ = [
    "Severity",
    "IssueSource",
    "IssueType",
    "ASTNodeType",
    "EditStatus",
    "ValidationStatus",
    "TrajectoryEventKind",
    "FixPlanStatus",
    "FailureCategory",
    "RoutingStrategy",
    "SCARemediationStage",
    "AgentActionStatus",
    "GroupRemediationStatus",
    "TaskStatus",
    # Constants
    "MAX_ANCESTRY_DEPTH",
    "MAX_TASK_QUEUE_SIZE",
    "CWEEntry",
    "LineRange",
    # Sandbox contracts
    "CommandResult",
    "VulnerabilityIssue",
    "LocalizedIssue",
    "FixPlan",
    "EditRequest",
    "EditResult",
    "ValidationResult",
    "PatchAttempt",
    "TrajectoryEvent",
    # Triage and QA contracts
    "SystemContext",
    "CVEEnrichment",
    "VulnerabilityGroup",
    "TriageResult",
    "QAEvaluation",
    "QAFailureEvidence",
    "WorkaroundPhase",
    "WorkaroundContext",
    "WorkaroundEdit",
    "WorkaroundReplayPlan",
    "BatchQAResult",
    "AgentActionSummary",
    "TaskAttemptSnapshot",
    "UpdateRetryDiagnostics",
    "WorkerExecutionDiagnostics",
    "WorkerAttemptResult",
    "QAAttemptResult",
    "StateConsistencyEvent",
    "SupervisorRetryPlan",
    "SupervisorDecision",
    # Task queue
    "TaskSpawnRequest",
    "RemediationTask",
]
